import { Routes } from '@angular/router';
import { HomeClienteComponent } from './components/home-cliente/home-cliente.component';
import { LoginComponent } from './components/login/login.component';
import { AutocadastroComponent } from './components/autocadastro/autocadastro.component';
import { HomeFuncionario } from './components/home-funcionario/home-funcionario';
import { EfetuarOrcamento } from './components/home-funcionario/efetuar-orcamento/efetuar-orcamento';
import { NovaSolicitacao } from './components/home-cliente/nova-solicitacao/nova-solicitacao';
import { EfetuarManutencao } from './components/home-funcionario/efetuar-manutencao/efetuar-manutencao';
import { DetalhesSolicitacao } from './components/home-cliente/detalhes-solicitacao/detalhes-solicitacao';
import { Orcamento } from './components/home-cliente/orcamento/orcamento';
import { Pagamento } from './components/home-cliente/pagamento/pagamento';
import { RelatorioReceitas } from './components/home-funcionario/relatorio-receitas/relatorio-receitas';
import { RelatorioCategoria } from './components/home-funcionario/relatorio-categoria/relatorio-categoria';
import { VisualizarSolicitacao } from './components/home-funcionario/visualizar-solicitacao/visualizar-solicitacao';

export const routes: Routes = [
  { path: 'home-cliente', component: HomeClienteComponent },
  { path: 'login', component: LoginComponent },
  { path: '', component: AutocadastroComponent },
  { path: 'home-funcionario', component: HomeFuncionario },
  { path: 'efetuar-orcamento', component: EfetuarOrcamento },
  { path: 'efetuar-orcamento/:id', component: EfetuarOrcamento },
  { path: 'nova-solicitacao', component: NovaSolicitacao },
  { path: 'efetuar-manutencao/:id', component: EfetuarManutencao },
  { path: 'detalhes-solicitacao/:id', component: DetalhesSolicitacao },
  { path: 'orcamento/:id', component: Orcamento },
  { path: 'pagamento/:id', component: Pagamento },
  { path: 'relatorio-receitas', component: RelatorioReceitas },
  { path: 'relatorio-categoria', component: RelatorioCategoria },
  { path: 'visualizar-solicitacao', component: VisualizarSolicitacao }, 
  { path: '**', redirectTo: '' },
];
